version: 2
jobs:
  test:
    docker:
      -
        image: 'circleci/node:10.16.3'
    working_directory: ~/app
    steps:
      - checkout
      -
        restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      -
        run: 'yarn install'
      -
        save_cache:
          name: Save Yarn Package Cache
          key: 'yarn-packages-{{ checksum "yarn.lock" }}'
          paths:
            - ~/.cache/yarn
      -
        run: 'yarn test'