version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build-staging:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$STAGING_DROPLET_IP "./deploy.sh"
  pull-and-build-production:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$PRODUCTION_DROPLET_IP "./deploy.sh"
# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build-staging:
          filters:
            branches:
              only:
                - staging
      - pull-and-build-production:
          filters:
            branches:
              only:
                - master